version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    links:
      - wordpress
    restart: always

  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=electro80
    restart: always

  wordpress:
    image: wordpress:php7.2-fpm
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=clown_db
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=JJ(1YsG3i;|dY:j
    links:
      - mysql
    restart: always

    phpmyadmin:
      image: corbinu/docker-phpmyadmin
      links:
        - wordpress_db:mysql
      ports:
        - 8181:80
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: electro80
      restart: always
